import { CardDefinition } from './types'

// ============================================
// NetRun - Card Definitions
// 40 unique cards across factions and types
// ============================================

export const ALL_CARDS: CardDefinition[] = [
  // ========== RUNNER PROGRAMS ==========
  {
    id: 'r_neural_spike',
    name: 'Neural Spike',
    type: 'program',
    faction: 'runner',
    rarity: 'common',
    strength: 3,
    firewall: 1,
    ramCost: 2,
    ability: 'Ataque rápido y directo',
    flavorText: '"Un pulso limpio. Sin rastro." - Phantom',
    artColors: ['#00ffff', '#0066ff'],
    artIcon: '⚡',
  },
  {
    id: 'r_data_leech',
    name: 'Data Leech',
    type: 'program',
    faction: 'runner',
    rarity: 'common',
    strength: 2,
    firewall: 2,
    ramCost: 2,
    ability: 'Drena 1 punto de vida al atacar',
    abilityEffect: { type: 'on_attack', effect: { action: 'drain', value: 1 } },
    flavorText: '"Lo que es tuyo, es mío." - Rogue_AI',
    artColors: ['#ff00ff', '#6600cc'],
    artIcon: '🧬',
  },
  {
    id: 'r_ghost_protocol',
    name: 'Ghost Protocol',
    type: 'program',
    faction: 'runner',
    rarity: 'uncommon',
    strength: 4,
    firewall: 2,
    ramCost: 3,
    ability: 'Ignora firewall al atacar',
    abilityEffect: { type: 'on_attack', effect: { action: 'pierce' } },
    flavorText: '"No puedes detener lo que no puedes ver."',
    artColors: ['#00ff88', '#004422'],
    artIcon: '👻',
  },
  {
    id: 'r_worm_cluster',
    name: 'Worm Cluster',
    type: 'program',
    faction: 'runner',
    rarity: 'uncommon',
    strength: 2,
    firewall: 3,
    ramCost: 3,
    ability: '+1 fuerza a todos los aliados al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'buff_all_allies', stat: 'strength', value: 1 } },
    flavorText: '"Se multiplican. Siempre se multiplican."',
    artColors: ['#ff4444', '#880000'],
    artIcon: '🐛',
  },
  {
    id: 'r_blackout',
    name: 'Blackout',
    type: 'program',
    faction: 'runner',
    rarity: 'rare',
    strength: 5,
    firewall: 3,
    ramCost: 4,
    ability: 'Ataca dos veces',
    abilityEffect: { type: 'on_attack', effect: { action: 'double_strike' } },
    flavorText: '"Las luces se apagaron. Ya era tarde."',
    artColors: ['#ff0066', '#330011'],
    artIcon: '🌑',
  },
  {
    id: 'r_zero_day',
    name: 'Zero Day Exploit',
    type: 'program',
    faction: 'runner',
    rarity: 'legendary',
    strength: 7,
    firewall: 4,
    ramCost: 6,
    ability: 'Destruye un enemigo al azar al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'destroy_random_enemy' } },
    flavorText: '"El día que la red se arrodilló." - Archivo Clasificado',
    artColors: ['#ff0000', '#ffff00'],
    artIcon: '💀',
  },
  {
    id: 'r_packet_sniffer',
    name: 'Packet Sniffer',
    type: 'program',
    faction: 'runner',
    rarity: 'common',
    strength: 1,
    firewall: 1,
    ramCost: 1,
    ability: 'Roba 1 carta al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'draw_cards', value: 1 } },
    flavorText: '"Cada byte cuenta."',
    artColors: ['#44ffff', '#006666'],
    artIcon: '📡',
  },
  {
    id: 'r_rootkit',
    name: 'Rootkit',
    type: 'program',
    faction: 'runner',
    rarity: 'rare',
    strength: 4,
    firewall: 5,
    ramCost: 5,
    ability: '+2 fuerza propia al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'buff_self', stat: 'strength', value: 2 } },
    flavorText: '"Acceso root concedido. Buena suerte."',
    artColors: ['#00ff00', '#003300'],
    artIcon: '🔓',
  },

  // ========== CORP ICE ==========
  {
    id: 'c_firewall_v1',
    name: 'Firewall v1',
    type: 'ice',
    faction: 'corp',
    rarity: 'common',
    strength: 1,
    firewall: 3,
    ramCost: 2,
    ability: 'Muro básico de defensa',
    flavorText: '"Primer nivel de protección." - Manual Corp',
    artColors: ['#ff8800', '#663300'],
    artIcon: '🔥',
  },
  {
    id: 'c_sentinel',
    name: 'Sentinel ICE',
    type: 'ice',
    faction: 'corp',
    rarity: 'common',
    strength: 2,
    firewall: 4,
    ramCost: 3,
    ability: 'Defensor confiable',
    flavorText: '"Nunca duerme. Nunca olvida."',
    artColors: ['#4488ff', '#001144'],
    artIcon: '🛡️',
  },
  {
    id: 'c_black_ice',
    name: 'Black ICE',
    type: 'ice',
    faction: 'corp',
    rarity: 'rare',
    strength: 3,
    firewall: 6,
    ramCost: 4,
    ability: 'Hace 2 de daño al atacante',
    abilityEffect: { type: 'on_defend', effect: { action: 'damage_opponent', value: 2 } },
    flavorText: '"Tocar Black ICE es sentir la muerte digital."',
    artColors: ['#000000', '#ff0044'],
    artIcon: '🖤',
  },
  {
    id: 'c_neural_barrier',
    name: 'Neural Barrier',
    type: 'ice',
    faction: 'corp',
    rarity: 'uncommon',
    strength: 2,
    firewall: 5,
    ramCost: 3,
    ability: '-1 fuerza a un enemigo al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'debuff_enemy', stat: 'strength', value: 1 } },
    flavorText: '"Tu mente es el campo de batalla."',
    artColors: ['#ff44ff', '#440044'],
    artIcon: '🧠',
  },
  {
    id: 'c_data_fort',
    name: 'Data Fort',
    type: 'ice',
    faction: 'corp',
    rarity: 'uncommon',
    strength: 1,
    firewall: 7,
    ramCost: 4,
    ability: '+1 firewall a todos los aliados al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'buff_all_allies', stat: 'firewall', value: 1 } },
    flavorText: '"Construido para resistir el apocalipsis digital."',
    artColors: ['#8888ff', '#222266'],
    artIcon: '🏰',
  },
  {
    id: 'c_killswitch',
    name: 'Killswitch Protocol',
    type: 'ice',
    faction: 'corp',
    rarity: 'legendary',
    strength: 5,
    firewall: 8,
    ramCost: 7,
    ability: 'Escudo 3 al jugar. Hace 3 de daño al atacante',
    abilityEffect: { type: 'on_play', effect: { action: 'shield', value: 3 } },
    flavorText: '"Protocolo final activado. Que Dios te ayude."',
    artColors: ['#ff0000', '#000000'],
    artIcon: '☠️',
  },
  {
    id: 'c_honeypot',
    name: 'Honeypot',
    type: 'ice',
    faction: 'corp',
    rarity: 'rare',
    strength: 1,
    firewall: 3,
    ramCost: 2,
    ability: 'Roba 2 cartas al ser destruida',
    abilityEffect: { type: 'on_death', effect: { action: 'draw_cards', value: 2 } },
    flavorText: '"Adelante, toca. Es exactamente lo que quiero."',
    artColors: ['#ffcc00', '#664400'],
    artIcon: '🍯',
  },
  {
    id: 'c_trace_daemon',
    name: 'Trace Daemon',
    type: 'ice',
    faction: 'corp',
    rarity: 'common',
    strength: 3,
    firewall: 2,
    ramCost: 2,
    ability: 'ICE agresivo con buen ataque',
    flavorText: '"Te encontré."',
    artColors: ['#ff6600', '#331100'],
    artIcon: '👁️',
  },

  // ========== NEUTRAL HARDWARE ==========
  {
    id: 'n_ram_upgrade',
    name: 'RAM Upgrade',
    type: 'hardware',
    faction: 'neutral',
    rarity: 'common',
    strength: 0,
    firewall: 1,
    ramCost: 1,
    ability: 'Gana 2 RAM al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'gain_ram', value: 2 } },
    flavorText: '"Más RAM, más poder."',
    artColors: ['#00ffaa', '#004433'],
    artIcon: '💾',
  },
  {
    id: 'n_neural_link',
    name: 'Neural Link',
    type: 'hardware',
    faction: 'neutral',
    rarity: 'uncommon',
    strength: 1,
    firewall: 2,
    ramCost: 2,
    ability: 'Roba 2 cartas al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'draw_cards', value: 2 } },
    flavorText: '"Conectado directamente al flujo de datos."',
    artColors: ['#44aaff', '#002244'],
    artIcon: '🔗',
  },
  {
    id: 'n_crypto_shield',
    name: 'Crypto Shield',
    type: 'hardware',
    faction: 'neutral',
    rarity: 'uncommon',
    strength: 0,
    firewall: 4,
    ramCost: 3,
    ability: 'Escudo 2 al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'shield', value: 2 } },
    flavorText: '"256 bits de pura protección."',
    artColors: ['#ffdd00', '#554400'],
    artIcon: '🔐',
  },
  {
    id: 'n_overclock',
    name: 'Overclock Module',
    type: 'hardware',
    faction: 'neutral',
    rarity: 'rare',
    strength: 2,
    firewall: 2,
    ramCost: 3,
    ability: '+2 fuerza a todos los aliados al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'buff_all_allies', stat: 'strength', value: 2 } },
    flavorText: '"Peligrosamente rápido."',
    artColors: ['#ff4400', '#ffaa00'],
    artIcon: '⚙️',
  },
  {
    id: 'n_quantum_core',
    name: 'Quantum Core',
    type: 'hardware',
    faction: 'neutral',
    rarity: 'legendary',
    strength: 3,
    firewall: 3,
    ramCost: 5,
    ability: 'Gana 3 RAM y roba 2 cartas al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'gain_ram', value: 3 } },
    flavorText: '"El corazón de una máquina imposible."',
    artColors: ['#aa00ff', '#00aaff'],
    artIcon: '💎',
  },
  {
    id: 'n_backup_drive',
    name: 'Backup Drive',
    type: 'hardware',
    faction: 'neutral',
    rarity: 'common',
    strength: 0,
    firewall: 3,
    ramCost: 2,
    ability: 'Restaura 3 puntos de integridad al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'heal_player', value: 3 } },
    flavorText: '"Siempre ten un plan B."',
    artColors: ['#00ff66', '#006622'],
    artIcon: '💿',
  },

  // ========== EVENTS ==========
  {
    id: 'e_system_purge',
    name: 'System Purge',
    type: 'event',
    faction: 'runner',
    rarity: 'rare',
    strength: 0,
    firewall: 0,
    ramCost: 4,
    ability: 'Destruye un enemigo al azar',
    abilityEffect: { type: 'on_play', effect: { action: 'destroy_random_enemy' } },
    flavorText: '"Borrando todo. Sin excepción."',
    artColors: ['#ff0044', '#ffaa00'],
    artIcon: '🧹',
  },
  {
    id: 'e_deep_scan',
    name: 'Deep Scan',
    type: 'event',
    faction: 'runner',
    rarity: 'common',
    strength: 0,
    firewall: 0,
    ramCost: 1,
    ability: 'Roba 3 cartas',
    abilityEffect: { type: 'on_play', effect: { action: 'draw_cards', value: 3 } },
    flavorText: '"Mira más profundo. Siempre hay más."',
    artColors: ['#00ccff', '#003344'],
    artIcon: '🔍',
  },
  {
    id: 'e_ddos_attack',
    name: 'DDoS Attack',
    type: 'event',
    faction: 'runner',
    rarity: 'uncommon',
    strength: 0,
    firewall: 0,
    ramCost: 3,
    ability: 'Hace 4 de daño directo al oponente',
    abilityEffect: { type: 'on_play', effect: { action: 'damage_opponent', value: 4 } },
    flavorText: '"Miles de paquetes. Un solo objetivo."',
    artColors: ['#ff0088', '#440022'],
    artIcon: '💥',
  },
  {
    id: 'e_patch_update',
    name: 'Patch Update',
    type: 'event',
    faction: 'corp',
    rarity: 'common',
    strength: 0,
    firewall: 0,
    ramCost: 2,
    ability: 'Restaura 4 puntos de integridad',
    abilityEffect: { type: 'on_play', effect: { action: 'heal_player', value: 4 } },
    flavorText: '"Vulnerabilidad corregida. Por ahora."',
    artColors: ['#00ff44', '#003311'],
    artIcon: '🩹',
  },
  {
    id: 'e_emp_blast',
    name: 'EMP Blast',
    type: 'event',
    faction: 'corp',
    rarity: 'rare',
    strength: 0,
    firewall: 0,
    ramCost: 5,
    ability: 'Hace 3 de daño y roba RAM al oponente',
    abilityEffect: { type: 'on_play', effect: { action: 'steal_ram', value: 2 } },
    flavorText: '"Un pulso electromagnético que lo cambia todo."',
    artColors: ['#ffff00', '#666600'],
    artIcon: '⚡',
  },
  {
    id: 'e_overclock_burst',
    name: 'Overclock Burst',
    type: 'event',
    faction: 'neutral',
    rarity: 'uncommon',
    strength: 0,
    firewall: 0,
    ramCost: 2,
    ability: '+2 fuerza a todos los aliados este turno',
    abilityEffect: { type: 'on_play', effect: { action: 'buff_all_allies', stat: 'strength', value: 2 } },
    flavorText: '"Forzando los límites del hardware."',
    artColors: ['#ff6600', '#ff0066'],
    artIcon: '🔥',
  },
  {
    id: 'e_reboot',
    name: 'Emergency Reboot',
    type: 'event',
    faction: 'neutral',
    rarity: 'uncommon',
    strength: 0,
    firewall: 0,
    ramCost: 3,
    ability: 'Restaura 5 de integridad y gana 1 RAM',
    abilityEffect: { type: 'on_play', effect: { action: 'heal_player', value: 5 } },
    flavorText: '"Reiniciando sistemas... Restauración completa."',
    artColors: ['#00ff88', '#004488'],
    artIcon: '🔄',
  },

  // ========== MORE RUNNER ==========
  {
    id: 'r_virus_inject',
    name: 'Virus Injection',
    type: 'program',
    faction: 'runner',
    rarity: 'uncommon',
    strength: 3,
    firewall: 1,
    ramCost: 2,
    ability: 'Hace 2 de daño directo al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'damage_opponent', value: 2 } },
    flavorText: '"Inyección directa en el mainframe."',
    artColors: ['#88ff00', '#224400'],
    artIcon: '🦠',
  },
  {
    id: 'r_crypto_miner',
    name: 'Crypto Miner',
    type: 'program',
    faction: 'runner',
    rarity: 'common',
    strength: 2,
    firewall: 2,
    ramCost: 2,
    ability: 'Gana 1 RAM al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'gain_ram', value: 1 } },
    flavorText: '"Minando recursos en la sombra."',
    artColors: ['#ffaa00', '#553300'],
    artIcon: '⛏️',
  },
  {
    id: 'r_shadow_runner',
    name: 'Shadow Runner',
    type: 'program',
    faction: 'runner',
    rarity: 'rare',
    strength: 6,
    firewall: 2,
    ramCost: 5,
    ability: 'Ignora firewall. Drena 2 al atacar',
    abilityEffect: { type: 'on_attack', effect: { action: 'pierce' } },
    flavorText: '"Nadie la ha visto. Pero todos la han sentido."',
    artColors: ['#6600ff', '#000033'],
    artIcon: '🥷',
  },

  // ========== MORE CORP ==========
  {
    id: 'c_proxy_wall',
    name: 'Proxy Wall',
    type: 'ice',
    faction: 'corp',
    rarity: 'common',
    strength: 1,
    firewall: 4,
    ramCost: 2,
    ability: 'Escudo 1 al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'shield', value: 1 } },
    flavorText: '"Redirigiendo... Acceso denegado."',
    artColors: ['#0088ff', '#002244'],
    artIcon: '🧱',
  },
  {
    id: 'c_corp_enforcer',
    name: 'Corp Enforcer',
    type: 'ice',
    faction: 'corp',
    rarity: 'rare',
    strength: 5,
    firewall: 5,
    ramCost: 5,
    ability: '-2 fuerza a un enemigo al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'debuff_enemy', stat: 'strength', value: 2 } },
    flavorText: '"La corporación siempre cobra."',
    artColors: ['#cc0000', '#440000'],
    artIcon: '⚔️',
  },
  {
    id: 'c_ai_guardian',
    name: 'AI Guardian',
    type: 'ice',
    faction: 'corp',
    rarity: 'legendary',
    strength: 6,
    firewall: 7,
    ramCost: 7,
    ability: '+2 firewall a todos los aliados al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'buff_all_allies', stat: 'firewall', value: 2 } },
    flavorText: '"Soy la última línea de defensa. Soy invencible."',
    artColors: ['#00ffff', '#ff00ff'],
    artIcon: '🤖',
  },

  // ========== MORE NEUTRAL ==========
  {
    id: 'n_data_broker',
    name: 'Data Broker',
    type: 'hardware',
    faction: 'neutral',
    rarity: 'common',
    strength: 2,
    firewall: 1,
    ramCost: 1,
    ability: 'Unidad económica básica',
    flavorText: '"Información es poder. Poder es dinero."',
    artColors: ['#44ff88', '#114422'],
    artIcon: '📊',
  },
  {
    id: 'n_stealth_chip',
    name: 'Stealth Chip',
    type: 'hardware',
    faction: 'neutral',
    rarity: 'rare',
    strength: 3,
    firewall: 3,
    ramCost: 4,
    ability: 'Escudo 2 y +1 fuerza a todos al jugar',
    abilityEffect: { type: 'on_play', effect: { action: 'shield', value: 2 } },
    flavorText: '"Invisible para los scanners."',
    artColors: ['#888888', '#222222'],
    artIcon: '🕶️',
  },
  {
    id: 'e_mass_recall',
    name: 'Mass Data Recall',
    type: 'event',
    faction: 'neutral',
    rarity: 'legendary',
    strength: 0,
    firewall: 0,
    ramCost: 4,
    ability: 'Roba 4 cartas y gana 2 RAM',
    abilityEffect: { type: 'on_play', effect: { action: 'draw_cards', value: 4 } },
    flavorText: '"Toda la información del mundo en un instante."',
    artColors: ['#ffaa00', '#ff0088'],
    artIcon: '🌐',
  },
]

export function getCardById(id: string): CardDefinition | undefined {
  return ALL_CARDS.find(c => c.id === id)
}

export function getCardsByFaction(faction: CardDefinition['faction']): CardDefinition[] {
  return ALL_CARDS.filter(c => c.faction === faction)
}

export function getCardsByType(type: CardDefinition['type']): CardDefinition[] {
  return ALL_CARDS.filter(c => c.type === type)
}

export function getCardsByRarity(rarity: CardDefinition['rarity']): CardDefinition[] {
  return ALL_CARDS.filter(c => c.rarity === rarity)
}

export function getStarterDeck(faction: 'runner' | 'corp'): string[] {
  const factionCards = ALL_CARDS.filter(c => c.faction === faction || c.faction === 'neutral')

  // Build a 20-card starter deck
  const deck: string[] = []
  const commons = factionCards.filter(c => c.rarity === 'common')
  const uncommons = factionCards.filter(c => c.rarity === 'uncommon')
  const rares = factionCards.filter(c => c.rarity === 'rare')

  // 2 copies of each common (up to fill)
  for (const card of commons) {
    deck.push(card.id, card.id)
  }
  // 1 copy of each uncommon
  for (const card of uncommons) {
    deck.push(card.id)
  }
  // 1 copy of each rare (if room)
  for (const card of rares) {
    if (deck.length < 20) deck.push(card.id)
  }

  return deck.slice(0, 20)
}
